### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/kamelmat-simple-counter#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Buen trabajo @kamelmat . Felicitaciones 😸
## Estilo de código y limpieza
- ¡Muy buen trabajo con tu código!
## Mejores prácticas/comentarios
- Poco que comentar Matías... has hecho un proyecto sobresaliente con todas las implementaciones que has añadido.

**Comment by kamelmat** [comment]
### Gracias @EduardoHernandezGuzman 🦾
Estoy disfrutando muchísimo todo lo que estoy aprendiendo!
